import type { CSSProperties } from "react"; import type { Metadata } from "next"; import Link from "next/link"; import { notFound } from "next/navigation"; import { Footer, Header } from "../../components"; import { stories } from "../../content";

// Prerender every story at build time. Without this the route is server-rendered
// on demand, which bills compute on every article view; as static files it costs
// nothing to serve. Anything not in `stories` still 404s via notFound() below.
export function generateStaticParams() { return stories.map((story) => ({ slug: story.slug })); }
export const dynamicParams = false;

export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const story=stories.find(s=>s.slug===slug);return story?{title:story.title,description:story.excerpt}:{};}

export default async function Post({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const story=stories.find(s=>s.slug===slug);if(!story)notFound();return <main className="story-article-page"><Header active="stories"/><div className="reading-thread" aria-hidden="true"><span/></div><article className="article"><header className="article-header shell"><p className="eyebrow">{story.category} · {story.place}</p><h1>{story.title}</h1><p>{story.excerpt}</p><div className="byline"><span>Words &amp; wandering by T</span><span>{story.date} · {story.read}</span></div></header><div className="article-hero photo" data-story-destination style={{backgroundImage:`url('${story.image}')`,viewTransitionName:`story-${story.slug}`} as CSSProperties}></div><div className="article-body"><p className="dropcap">The city was awake before I was. Somewhere under the porticoes, cups met saucers and shutters rolled upward with the clatter of a day beginning.</p><p>I had made a plan, naturally. Then the first side street offered a fruit stall, an old paper shop, and a patch of morning light so good that the plan was quietly retired.</p><h2>The pleasure of looking slowly</h2><p>Travel gets better when the checklist loosens its grip. I stopped for a coffee taken standing up, watched bicycles thread through the square, and followed a woman carrying an unreasonable number of flowers.</p><blockquote>“The best parts of a place rarely announce themselves.”</blockquote><p>By lunch, my pockets held a paper receipt, two market cherries, and the name of a cheese I could not pronounce. A perfectly successful morning.</p><figure><div className="article-inline photo"></div><figcaption>Proof that a wrong turn can be the whole point.</figcaption></figure><h2>Notes to bring home</h2><ul><li>Go out before breakfast at least once.</li><li>Always ask the market vendor what they would choose.</li><li>Leave enough room in the bag for something impractical.</li></ul><p>And when you think you have seen the whole street, turn around. Cities are generous like that.</p><Link className="text-link" href="/travel-stories">← Back to all travel stories</Link></div></article><Footer/></main>}
