export type Story = { slug:string; category:string; place:string; title:string; excerpt:string; image:string; date:string; read:string; };
export const stories: Story[] = [
  {slug:"bologna-before-breakfast",category:"Travel story",place:"Bologna, Italy",title:"Bologna before breakfast",excerpt:"Porticoes, pink morning light, and the particular joy of having nowhere urgent to be.",image:"https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1600&q=85",date:"June 18, 2026",read:"6 min read"},
  {slug:"blue-hour-lisbon",category:"City notes",place:"Lisbon, Portugal",title:"Lisbon at the blue hour",excerpt:"A tram, three miradouros, and the tiled doorway I nearly walked past.",image:"https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1200&q=85",date:"May 29, 2026",read:"5 min read"},
  {slug:"rainy-sunday-paris",category:"Weekend away",place:"Paris, France",title:"A rainy Sunday in Paris",excerpt:"The case for wet pavements, warm bread, and one very small museum.",image:"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=85",date:"April 12, 2026",read:"7 min read"},
  {slug:"train-to-lake-como",category:"Slow travel",place:"Lombardy, Italy",title:"The little train to Lake Como",excerpt:"Window seats, missed stops, and a lunch that took all afternoon.",image:"https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?auto=format&fit=crop&w=1200&q=85",date:"March 8, 2026",read:"8 min read"},
];
export const finds = [
  {name:"A striped linen tea towel",place:"Arles, France",note:"Too cheerful to leave behind.",image:"https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=900&q=85"},
  {name:"Three tiny olive forks",place:"Athens, Greece",note:"Necessary? No. Perfect? Yes.",image:"https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=85"},
  {name:"A very serious plum jug",place:"Porto, Portugal",note:"Made it home in one piece.",image:"https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=85"},
  {name:"The market basket",place:"Palermo, Italy",note:"Still carrying everything.",image:"https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=900&q=85"},
];
export const videos = [{title:"A slow market morning in Provence",description:"Come for the peaches, stay for the cheese counter and the world’s friendliest dog.",youtube:"https://www.youtube.com/",image:"https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1600&q=85"},{title:"48 hours in Lisbon",description:"Trams, tiles, tinned fish, repeat.",youtube:"https://www.youtube.com/",image:"https://images.unsplash.com/photo-1513735492246-483525079686?auto=format&fit=crop&w=1200&q=85"}];
